plugins {
    id 'com.android.application'
}

android {
    namespace 'de.boostertracker.scanner'
    compileSdk 34

    defaultConfig {
        applicationId 'de.boostertracker.scanner'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
}
